[2025-02-20 09:09:37,166] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 356, in ManagementSop_summary
    addPermission, deletePermission = 1
TypeError: cannot unpack non-iterable int object
[2025-02-20 09:09:37,174] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /SpecDownload/ManagementSop-summary/ 500 [0.22, 127.0.0.1:57473]
[2025-02-20 09:09:37,273] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:57473]
[2025-02-20 09:10:02,923] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:57699]
[2025-02-20 09:10:03,036] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:57713]
[2025-02-20 09:10:03,092] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57713]
[2025-02-20 09:10:03,338] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:10:03 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:10:03,352] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.14, 127.0.0.1:57699]
[2025-02-20 09:10:03,401] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.15, 127.0.0.1:57706]
[2025-02-20 09:13:54,910] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:58503]
[2025-02-20 09:13:55,006] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:58511]
[2025-02-20 09:13:55,069] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:58511]
[2025-02-20 09:13:55,211] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:13:55 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:13:55,222] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:58503]
[2025-02-20 09:13:55,253] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:58504]
[2025-02-20 09:14:14,982] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:14:14 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:14:14,991] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.12, 127.0.0.1:58504]
[2025-02-20 09:14:17,415] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:14:17 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:14:17,425] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:58504]
[2025-02-20 09:14:19,229] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:58504]
[2025-02-20 09:14:19,234] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:58503]
[2025-02-20 09:14:19,240] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:58658]
[2025-02-20 09:14:19,244] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.02, 127.0.0.1:58660]
[2025-02-20 09:14:34,184] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:14:34 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:14:34,194] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:58660]
[2025-02-20 09:14:38,856] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:14:38 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:14:38,865] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:58660]
[2025-02-20 09:23:18,046] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 375, in ManagementSop_summary
    if SpecDownload.objects.filter(Num=Num):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1164, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1028, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'Num' into field. Choices are: Case_name, Category, Customer, Functionn, Project, Version, edit_time, editor, files_Spec, id
[2025-02-20 09:23:18,050] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:23:18 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:23:18,060] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.28, 127.0.0.1:60389]
[2025-02-20 09:23:49,128] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:23:49 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:23:49,145] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.21, 127.0.0.1:60481]
[2025-02-20 09:25:30,064] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:60844]
[2025-02-20 09:25:30,151] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:60844]
[2025-02-20 09:25:30,182] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:60844]
[2025-02-20 09:25:30,227] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60856]
[2025-02-20 09:25:30,260] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60856]
[2025-02-20 09:25:30,298] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:60844]
[2025-02-20 09:25:30,301] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:60842]
[2025-02-20 09:25:30,458] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:25:30 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:25:30,468] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:60842]
[2025-02-20 09:25:30,498] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:60844]
[2025-02-20 09:26:30,829] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:26:30 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:26:30,848] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.10, 127.0.0.1:60844]
[2025-02-20 09:26:32,459] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:26:32 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:26:32,469] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.11, 127.0.0.1:60844]
[2025-02-20 09:30:28,431] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:61914]
[2025-02-20 09:30:28,508] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:61914]
[2025-02-20 09:30:28,522] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61914]
[2025-02-20 09:30:28,574] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61923]
[2025-02-20 09:30:28,619] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61923]
[2025-02-20 09:30:28,655] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61914]
[2025-02-20 09:30:28,659] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61917]
[2025-02-20 09:30:28,798] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:30:28 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:30:28,808] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:61917]
[2025-02-20 09:30:28,846] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:61917]
[2025-02-20 09:30:42,306] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:30:42 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:30:42,320] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:61917]
[2025-02-20 09:50:05,114] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:50:05 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:50:05,131] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.11, 127.0.0.1:50818]
[2025-02-20 09:50:23,698] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:50:23 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:50:23,705] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:50818]
[2025-02-20 09:50:53,404] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:50:53 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:50:53,428] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.26, 127.0.0.1:51098]
[2025-02-20 09:50:54,535] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:50:54 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:50:54,544] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.10, 127.0.0.1:51098]
[2025-02-20 09:50:58,054] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /media/files_SopRom/autoit-v3-setup_P04LASh.exe 200 [0.09, 127.0.0.1:51098]
[2025-02-20 09:51:19,962] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.15, 127.0.0.1:51098]
[2025-02-20 09:51:20,054] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.09, 127.0.0.1:51098]
[2025-02-20 09:51:20,205] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:51098]
[2025-02-20 09:51:22,785] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:51:22 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /admin/login/ POST
[2025-02-20 09:51:22,795] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.21, 127.0.0.1:51098]
[2025-02-20 09:51:23,980] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [1.18, 127.0.0.1:51098]
[2025-02-20 09:51:24,033] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/simpleui-x/css/index.css.map 304 [0.00, 127.0.0.1:51098]
[2025-02-20 09:51:24,111] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/simpleui-x/waves/waves.min.js.map 304 [0.00, 127.0.0.1:51098]
[2025-02-20 09:51:24,238] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:51098]
[2025-02-20 09:52:09,198] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/ 200 [0.10, 127.0.0.1:51098]
[2025-02-20 09:52:09,258] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.13, 127.0.0.1:51022]
[2025-02-20 09:52:09,287] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:51098]
[2025-02-20 09:52:09,324] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/simpleui-x/theme/simpleui.css.map 304 [0.00, 127.0.0.1:51098]
[2025-02-20 09:52:11,149] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/3/change/ 200 [0.13, 127.0.0.1:51098]
[2025-02-20 09:52:11,216] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:51098]
[2025-02-20 09:52:18,178] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/ 200 [0.11, 127.0.0.1:51098]
[2025-02-20 09:52:25,094] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 09:52:25 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 09:52:25,103] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:51098]
[2025-02-20 09:52:29,432] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [1.00, 127.0.0.1:51098]
[2025-02-20 09:52:29,664] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/ 200 [0.10, 127.0.0.1:51098]
[2025-02-20 09:52:29,700] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:51098]
[2025-02-20 09:52:29,786] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:51098]
[2025-02-20 09:52:30,594] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/add/ 200 [0.09, 127.0.0.1:51098]
[2025-02-20 09:52:30,655] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:51098]
[2025-02-20 10:00:33,698] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:00:33 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:00:33,717] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.41, 127.0.0.1:50860]
[2025-02-20 10:00:34,880] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:00:34 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:00:34,899] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.22, 127.0.0.1:50860]
[2025-02-20 10:00:47,762] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:00:47 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:00:47,784] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:50860]
[2025-02-20 10:12:03,407] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:12:03 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:12:03,421] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.11, 127.0.0.1:51068]
[2025-02-20 10:12:10,560] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 412, in ManagementSop_summary
    instance = ManagementSopRoom.objects.get(id=1)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
SpecDownload.models.ManagementSopRoom.DoesNotExist: ManagementSopRoom matching query does not exist.
[2025-02-20 10:12:10,562] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:12:10 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:12:10,564] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.15, 127.0.0.1:51068]
[2025-02-20 10:12:40,451] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 409, in ManagementSop_summary
    ManagementSopRoom.objects.get(id=i).files_Spec.all().delete()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
SpecDownload.models.ManagementSopRoom.DoesNotExist: ManagementSopRoom matching query does not exist.
[2025-02-20 10:12:40,454] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:12:40 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:12:40,461] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.14, 127.0.0.1:50839]
[2025-02-20 10:14:38,042] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 409, in ManagementSop_summary
    ManagementSopRoom.objects.get(id=i).files_Spec.all().delete()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
SpecDownload.models.ManagementSopRoom.DoesNotExist: ManagementSopRoom matching query does not exist.
[2025-02-20 10:14:38,042] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:14:38 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:14:38,044] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.06, 127.0.0.1:51057]
[2025-02-20 10:14:54,686] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:51057]
[2025-02-20 10:14:54,770] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51057]
[2025-02-20 10:14:54,803] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51057]
[2025-02-20 10:14:54,847] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52146]
[2025-02-20 10:14:54,885] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52146]
[2025-02-20 10:14:54,947] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51057]
[2025-02-20 10:14:54,955] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:51697]
[2025-02-20 10:14:55,120] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:14:55 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:14:55,131] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:51697]
[2025-02-20 10:14:55,189] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:51057]
[2025-02-20 10:15:12,529] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:15:12 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:15:12,559] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.26, 127.0.0.1:51057]
[2025-02-20 10:15:13,262] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:15:13 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:15:13,271] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.14, 127.0.0.1:51057]
[2025-02-20 10:15:20,171] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 412, in ManagementSop_summary
    instance = ManagementSopRoom.objects.get(id=i)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
SpecDownload.models.ManagementSopRoom.DoesNotExist: ManagementSopRoom matching query does not exist.
[2025-02-20 10:15:20,172] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:15:20 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:15:20,174] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.11, 127.0.0.1:50819]
[2025-02-20 10:15:32,571] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:50819]
[2025-02-20 10:15:32,586] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52146]
[2025-02-20 10:15:32,668] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:50819]
[2025-02-20 10:15:32,682] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:50819]
[2025-02-20 10:15:32,730] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51007]
[2025-02-20 10:15:32,733] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51007]
[2025-02-20 10:15:32,805] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:50819]
[2025-02-20 10:15:32,810] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50999]
[2025-02-20 10:15:32,932] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:15:32 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:15:32,945] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:50999]
[2025-02-20 10:15:32,993] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:50999]
[2025-02-20 10:16:35,303] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:16:35 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:16:35,351] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.34, 127.0.0.1:50879]
[2025-02-20 10:16:36,531] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:16:36 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:16:36,541] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.13, 127.0.0.1:50879]
[2025-02-20 10:16:42,671] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 413, in ManagementSop_summary
    files_SopRom_delete(instance)
TypeError: files_SopRom_delete() missing 1 required positional argument: 'instance'
[2025-02-20 10:16:42,673] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:16:42 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:16:42,675] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.24, 127.0.0.1:50879]
[2025-02-20 10:18:07,586] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:51024]
[2025-02-20 10:18:07,649] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51024]
[2025-02-20 10:18:07,664] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51024]
[2025-02-20 10:18:07,681] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51032]
[2025-02-20 10:18:07,723] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51032]
[2025-02-20 10:18:07,728] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51024]
[2025-02-20 10:18:07,734] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51025]
[2025-02-20 10:18:07,844] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:18:07 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:18:07,854] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:51025]
[2025-02-20 10:18:07,918] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:51025]
[2025-02-20 10:18:16,104] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:18:16 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:18:16,115] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.17, 127.0.0.1:51025]
[2025-02-20 10:18:17,727] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:18:17 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:18:17,735] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.10, 127.0.0.1:51025]
[2025-02-20 10:18:23,449] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 413, in ManagementSop_summary
    files_SopRom_delete(instance)
TypeError: files_SopRom_delete() missing 1 required positional argument: 'instance'
[2025-02-20 10:18:23,451] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:18:23 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:18:23,453] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.14, 127.0.0.1:51025]
[2025-02-20 10:24:44,003] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:50809]
[2025-02-20 10:24:44,081] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:50809]
[2025-02-20 10:24:44,123] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:50809]
[2025-02-20 10:24:44,162] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50819]
[2025-02-20 10:24:44,199] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50819]
[2025-02-20 10:24:44,238] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50809]
[2025-02-20 10:24:44,243] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:50811]
[2025-02-20 10:24:44,400] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:24:44 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:24:44,410] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:50811]
[2025-02-20 10:24:44,471] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:50811]
[2025-02-20 10:24:48,479] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /SpecDownload/ManagementSop-summary/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\views.py", line 414, in ManagementSop_summary
    files_SopRom_delete(sender, instance)
  File "C:\djangoproject\Reliability_Row_data\SpecDownload\models.py", line 38, in files_SopRom_delete
    instance.files.delete(False)
AttributeError: 'ManagementSopRoom' object has no attribute 'files'
[2025-02-20 10:24:48,480] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:24:48 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:24:48,482] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /SpecDownload/ManagementSop-summary/ 500 [0.21, 127.0.0.1:50811]
[2025-02-20 10:29:20,763] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:50874]
[2025-02-20 10:29:20,855] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:50874]
[2025-02-20 10:29:20,866] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:50874]
[2025-02-20 10:29:20,921] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50880]
[2025-02-20 10:29:20,959] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50880]
[2025-02-20 10:29:21,000] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:50874]
[2025-02-20 10:29:21,003] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50866]
[2025-02-20 10:29:21,149] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:29:21 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:29:21,163] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:50866]
[2025-02-20 10:29:21,202] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:50874]
[2025-02-20 10:29:25,313] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:29:25 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:29:25,323] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:50874]
[2025-02-20 10:30:25,930] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:30:25 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:30:25,957] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.28, 127.0.0.1:50832]
[2025-02-20 10:30:28,464] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:30:28 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:30:28,493] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.15, 127.0.0.1:50832]
[2025-02-20 10:30:40,793] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:30:40 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:30:40,803] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:50832]
[2025-02-20 10:34:21,365] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:34:21 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:34:21,407] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.17, 127.0.0.1:63411]
[2025-02-20 10:34:31,469] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:34:31 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:34:31,484] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:63411]
[2025-02-20 10:34:36,411] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:34:36 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:34:36,422] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:63411]
[2025-02-20 10:40:49,122] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:51074]
[2025-02-20 10:40:49,244] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51074]
[2025-02-20 10:40:49,284] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51074]
[2025-02-20 10:40:49,352] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51091]
[2025-02-20 10:40:49,416] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51091]
[2025-02-20 10:40:49,467] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51074]
[2025-02-20 10:40:49,516] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51074]
[2025-02-20 10:40:49,691] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:40:49 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:40:49,704] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:51074]
[2025-02-20 10:40:49,770] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:51074]
[2025-02-20 10:40:54,022] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:40:54 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:40:54,034] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:51074]
[2025-02-20 10:41:01,432] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:41:01 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:41:01,445] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.24, 127.0.0.1:51074]
[2025-02-20 10:41:02,322] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:41:02 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:41:02,333] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.14, 127.0.0.1:51074]
[2025-02-20 10:42:02,990] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:50879]
[2025-02-20 10:42:02,995] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:50880]
[2025-02-20 10:42:02,999] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50881]
[2025-02-20 10:42:03,114] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:50881]
[2025-02-20 10:43:18,963] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:60424]
[2025-02-20 10:43:18,976] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51091]
[2025-02-20 10:43:19,063] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:60424]
[2025-02-20 10:43:19,077] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:60424]
[2025-02-20 10:43:19,159] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60895]
[2025-02-20 10:43:19,162] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60895]
[2025-02-20 10:43:19,242] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:60424]
[2025-02-20 10:43:19,280] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:60424]
[2025-02-20 10:43:19,395] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:43:19 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:43:19,405] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:60424]
[2025-02-20 10:43:19,471] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:60424]
[2025-02-20 10:45:01,976] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:58336]
[2025-02-20 10:45:01,986] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60895]
[2025-02-20 10:45:02,053] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:58336]
[2025-02-20 10:45:02,065] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:58336]
[2025-02-20 10:45:02,083] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59077]
[2025-02-20 10:45:02,086] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59077]
[2025-02-20 10:45:02,134] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:58336]
[2025-02-20 10:45:02,139] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:58757]
[2025-02-20 10:45:02,237] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:45:02 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:45:02,246] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:58757]
[2025-02-20 10:45:02,289] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:58757]
[2025-02-20 10:47:50,504] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:50844]
[2025-02-20 10:47:50,513] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59077]
[2025-02-20 10:47:50,574] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:50844]
[2025-02-20 10:47:50,594] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:50844]
[2025-02-20 10:47:50,618] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50854]
[2025-02-20 10:47:50,621] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50854]
[2025-02-20 10:47:50,690] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:50844]
[2025-02-20 10:47:50,701] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:50847]
[2025-02-20 10:47:50,864] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:47:50 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:47:50,873] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:50847]
[2025-02-20 10:47:50,914] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:50847]
[2025-02-20 10:47:59,151] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:47:59 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:47:59,163] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:50847]
[2025-02-20 10:48:08,583] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:48:08 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:48:08,595] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.20, 127.0.0.1:50847]
[2025-02-20 10:48:10,304] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:48:10 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:48:10,314] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.12, 127.0.0.1:50847]
[2025-02-20 10:49:40,866] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:49:40 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:49:40,885] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:50993]
[2025-02-20 10:50:52,536] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:50:52 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:50:52,561] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.18, 127.0.0.1:63760]
[2025-02-20 10:51:01,252] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63760]
[2025-02-20 10:51:01,258] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:50819]
[2025-02-20 10:51:01,264] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50844]
[2025-02-20 10:51:01,392] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:50844]
[2025-02-20 10:51:06,426] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:51:06 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:51:06,454] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.09, 127.0.0.1:50844]
[2025-02-20 10:56:58,463] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.10, 127.0.0.1:59642]
[2025-02-20 10:56:58,552] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:59642]
[2025-02-20 10:56:58,581] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59642]
[2025-02-20 10:56:58,628] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59713]
[2025-02-20 10:56:58,691] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59713]
[2025-02-20 10:56:58,728] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:59642]
[2025-02-20 10:56:58,734] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:59647]
[2025-02-20 10:56:58,868] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:56:58 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:56:58,881] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:59647]
[2025-02-20 10:56:58,942] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:59647]
[2025-02-20 10:58:42,945] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:62854]
[2025-02-20 10:58:43,039] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:62854]
[2025-02-20 10:58:43,052] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:62854]
[2025-02-20 10:58:43,107] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:62899]
[2025-02-20 10:58:43,153] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62899]
[2025-02-20 10:58:43,186] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:62854]
[2025-02-20 10:58:43,192] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:62865]
[2025-02-20 10:58:43,339] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:58:43 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:58:43,349] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:62865]
[2025-02-20 10:58:43,375] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:62854]
[2025-02-20 10:58:59,337] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:58:59 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:58:59,367] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.48, 127.0.0.1:62854]
[2025-02-20 10:59:00,404] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:59:00 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:59:00,414] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.20, 127.0.0.1:62854]
[2025-02-20 10:59:06,480] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:59:06 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:59:06,491] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:62854]
[2025-02-20 10:59:25,340] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:59:25 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:59:25,366] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:62854]
[2025-02-20 10:59:55,695] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:59:55 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:59:55,705] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.44, 127.0.0.1:62854]
[2025-02-20 10:59:57,000] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 10:59:57 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 10:59:57,010] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.12, 127.0.0.1:62854]
[2025-02-20 11:00:11,495] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:11 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:11,505] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:62854]
[2025-02-20 11:00:25,001] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:25 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:25,024] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:62854]
[2025-02-20 11:00:28,834] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:28 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:28,848] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:62854]
[2025-02-20 11:00:29,515] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:29 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:29,526] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:62854]
[2025-02-20 11:00:29,703] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:29 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:29,718] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:62854]
[2025-02-20 11:00:29,834] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:29 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:29,845] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:62854]
[2025-02-20 11:00:43,202] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:43 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:43,219] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:62854]
[2025-02-20 11:00:45,357] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:45 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:45,368] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:62854]
[2025-02-20 11:00:59,227] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:00:59 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:00:59,236] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:62854]
[2025-02-20 11:01:13,685] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:01:13 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:01:13,724] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:62854]
[2025-02-20 11:02:23,649] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:51544]
[2025-02-20 11:02:23,662] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62899]
[2025-02-20 11:02:23,732] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51544]
[2025-02-20 11:02:23,744] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:51544]
[2025-02-20 11:02:23,768] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51557]
[2025-02-20 11:02:23,771] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51557]
[2025-02-20 11:02:23,810] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:51544]
[2025-02-20 11:02:23,816] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51545]
[2025-02-20 11:02:23,920] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:02:23 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:02:23,932] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:51545]
[2025-02-20 11:02:23,982] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:51545]
[2025-02-20 11:02:32,959] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:02:32 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:02:32,970] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:51545]
[2025-02-20 11:02:48,771] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:02:48 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:02:48,780] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:51545]
[2025-02-20 11:07:06,234] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.05, 127.0.0.1:52849]
[2025-02-20 11:07:06,243] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51557]
[2025-02-20 11:07:06,321] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:52849]
[2025-02-20 11:07:06,332] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52849]
[2025-02-20 11:07:06,352] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52855]
[2025-02-20 11:07:06,360] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52855]
[2025-02-20 11:07:06,395] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:52849]
[2025-02-20 11:07:06,401] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52852]
[2025-02-20 11:07:06,485] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:07:06 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:07:06,496] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.03, 127.0.0.1:52852]
[2025-02-20 11:07:06,547] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:52852]
[2025-02-20 11:07:47,595] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:53021]
[2025-02-20 11:07:47,803] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:53021]
[2025-02-20 11:07:47,869] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:53021]
[2025-02-20 11:07:47,954] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:53028]
[2025-02-20 11:07:47,994] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:53028]
[2025-02-20 11:07:48,065] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:53021]
[2025-02-20 11:07:48,117] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:53021]
[2025-02-20 11:07:48,528] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:07:48 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:07:48,543] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:53021]
[2025-02-20 11:07:48,609] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:53021]
[2025-02-20 11:10:10,015] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/ 200 [0.53, 127.0.0.1:54177]
[2025-02-20 11:11:05,421] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.49, 127.0.0.1:54177]
[2025-02-20 11:11:05,473] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.51, 127.0.0.1:54810]
[2025-02-20 11:11:05,497] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:54177]
[2025-02-20 11:11:23,929] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/add/ 200 [0.43, 127.0.0.1:54177]
[2025-02-20 11:11:23,981] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:54177]
[2025-02-20 11:11:24,116] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/icon-unknown.svg 304 [0.01, 127.0.0.1:54177]
[2025-02-20 11:11:24,119] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/icon-unknown-alt.svg 304 [0.01, 127.0.0.1:54810]
[2025-02-20 11:12:47,166] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:12:47 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /admin/app01/role/add/ POST
[2025-02-20 11:12:47,205] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/app01/role/add/ 302 [0.12, 127.0.0.1:55848]
[2025-02-20 11:12:49,566] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [2.36, 127.0.0.1:55848]
[2025-02-20 11:12:49,694] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:55848]
[2025-02-20 11:14:43,422] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/35/change/ 200 [0.57, 127.0.0.1:57262]
[2025-02-20 11:14:43,473] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:57262]
[2025-02-20 11:14:50,984] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.19, 127.0.0.1:57262]
[2025-02-20 11:16:29,888] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/?o=5.-6 200 [0.16, 127.0.0.1:58249]
[2025-02-20 11:16:29,975] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:58249]
[2025-02-20 11:16:31,480] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/ 200 [0.14, 127.0.0.1:58249]
[2025-02-20 11:16:35,849] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/SpecDownload/managementsoproom/?o=5.-6 200 [0.19, 127.0.0.1:58249]
[2025-02-20 11:16:35,922] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:58249]
[2025-02-20 11:18:31,728] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:18:31 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:18:31,883] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.67, 127.0.0.1:59612]
[2025-02-20 11:18:45,471] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:18:45 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:18:45,486] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.15, 127.0.0.1:59612]
[2025-02-20 11:18:46,214] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-20 11:18:46 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /SpecDownload/ManagementSop-summary/ POST
[2025-02-20 11:18:46,227] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:59612]
[2025-02-20 11:26:09,089] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [0.74, 127.0.0.1:52363]
[2025-02-20 11:26:09,126] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.63, 127.0.0.1:52367]
[2025-02-20 11:26:09,151] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:52363]
[2025-02-20 11:26:21,026] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/134/change/ 200 [0.27, 127.0.0.1:52363]
[2025-02-20 11:26:21,084] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:52363]
[2025-02-20 11:27:46,848] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [0.35, 127.0.0.1:57064]
[2025-02-20 11:27:46,907] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:57064]
[2025-02-20 11:27:51,634] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.28, 127.0.0.1:57064]
[2025-02-20 11:27:51,667] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.29, 127.0.0.1:57129]
[2025-02-20 11:27:51,703] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:57064]
[2025-02-20 11:28:42,022] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/35/change/ 200 [0.48, 127.0.0.1:57064]
[2025-02-20 11:28:42,098] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:57064]
[2025-02-20 11:42:02,687] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/menu/ 200 [0.22, 127.0.0.1:63420]
[2025-02-20 11:42:02,723] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.24, 127.0.0.1:63425]
[2025-02-20 11:42:02,752] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:63420]
[2025-02-20 11:42:41,305] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/menu/45/change/ 200 [0.15, 127.0.0.1:63420]
[2025-02-20 11:42:41,382] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:63420]
[2025-02-20 11:43:19,451] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:63420]
[2025-02-20 11:43:44,097] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/133/change/ 200 [0.13, 127.0.0.1:63420]
[2025-02-20 11:43:44,203] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:63420]
[2025-02-20 11:44:10,886] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [0.34, 127.0.0.1:63420]
[2025-02-20 11:44:10,938] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:63420]
[2025-02-20 11:44:13,098] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/132/change/ 200 [0.21, 127.0.0.1:63420]
[2025-02-20 11:44:13,195] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:63420]
[2025-02-20 11:44:32,478] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [0.36, 127.0.0.1:63420]
[2025-02-20 11:44:33,928] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/131/change/ 200 [0.11, 127.0.0.1:63420]
[2025-02-20 11:44:34,026] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:63420]
[2025-02-20 13:52:05,194] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:53713]
[2025-02-20 13:52:45,972] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:53713]
[2025-02-20 14:12:08,326] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:51144]
[2025-02-20 14:12:11,545] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:51144]
[2025-02-20 15:52:31,580] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:53549]
[2025-02-21 09:53:12,360] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 302 [0.03, 127.0.0.1:55805]
[2025-02-21 09:53:12,401] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.03, 127.0.0.1:55805]
[2025-02-21 09:53:12,621] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.03, 127.0.0.1:55805]
[2025-02-21 09:53:12,635] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.00, 127.0.0.1:55805]
[2025-02-21 09:53:15,382] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 09:53:15 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /login/ POST
[2025-02-21 09:53:15,421] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /login/?next= 302 [0.34, 127.0.0.1:55805]
[2025-02-21 09:53:15,486] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /login/ 302 [0.06, 127.0.0.1:55805]
[2025-02-21 09:53:15,555] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.06, 127.0.0.1:55805]
[2025-02-21 09:53:15,752] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:55850]
[2025-02-21 09:53:15,943] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55850]
[2025-02-21 09:53:16,029] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:55805]
[2025-02-21 09:53:19,058] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 302 [0.04, 127.0.0.1:55805]
[2025-02-21 09:53:19,122] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/app01/permission/ 200 [0.06, 127.0.0.1:55805]
[2025-02-21 09:53:19,277] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.02, 127.0.0.1:55805]
[2025-02-21 09:53:19,328] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.05, 127.0.0.1:55805]
[2025-02-21 09:53:19,533] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:55805]
[2025-02-21 09:53:22,967] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 09:53:22 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /admin/login/ POST
[2025-02-21 09:53:22,975] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.19, 127.0.0.1:55805]
[2025-02-21 09:53:23,962] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.98, 127.0.0.1:55805]
[2025-02-21 09:53:24,177] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:55805]
[2025-02-21 10:05:12,372] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.13, 127.0.0.1:62889]
[2025-02-21 10:05:12,423] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.17, 127.0.0.1:62897]
[2025-02-21 10:05:12,468] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:62889]
[2025-02-21 10:06:36,227] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.66, 127.0.0.1:63718]
[2025-02-21 10:06:37,443] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.07, 127.0.0.1:63718]
[2025-02-21 10:06:37,501] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:63718]
[2025-02-21 10:06:37,629] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:63718]
[2025-02-21 10:06:53,448] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.79, 127.0.0.1:63718]
[2025-02-21 10:06:54,753] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.19, 127.0.0.1:63718]
[2025-02-21 10:06:54,790] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:63718]
[2025-02-21 10:06:54,913] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:63718]
[2025-02-21 10:06:56,274] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:63718]
[2025-02-21 10:06:57,708] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 302 [0.04, 127.0.0.1:63718]
[2025-02-21 10:06:58,595] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.88, 127.0.0.1:63718]
[2025-02-21 10:06:59,146] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [0.44, 127.0.0.1:63718]
[2025-02-21 10:06:59,323] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:63718]
[2025-02-21 10:07:01,862] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.00, 127.0.0.1:63718]
[2025-02-21 10:07:01,897] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.02, 127.0.0.1:63722]
[2025-02-21 10:07:01,939] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:63718]
[2025-02-21 10:17:38,084] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.68, 127.0.0.1:52431]
[2025-02-21 10:17:39,313] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.11, 127.0.0.1:52431]
[2025-02-21 10:17:39,368] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:52431]
[2025-02-21 10:17:49,651] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Python372\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Python372\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 32, in process_request
    permission_url = request.session.get(settings.SESSION_PERMISSION_URL_KEY)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 66, in get
    return self._session.get(key, default)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 393, in get
    num = len(clone)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 250, in __len__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (timed out)")
[2025-02-21 10:17:49,661] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [10.20, 127.0.0.1:52431]
[2025-02-21 10:17:51,568] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.59, 127.0.0.1:52431]
[2025-02-21 10:17:53,363] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.68, 127.0.0.1:52431]
[2025-02-21 10:17:53,675] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/jsi18n/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Python372\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Python372\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 241, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 212, in inner
    if not self.has_permission(request):
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 213, in inner
    self._setup()
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\auth\middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\auth\middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\auth\__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\auth\__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 393, in get
    num = len(clone)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 250, in __len__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")
[2025-02-21 10:17:53,883] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/jsi18n/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Python372\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Python372\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 32, in process_request
    permission_url = request.session.get(settings.SESSION_PERMISSION_URL_KEY)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 66, in get
    return self._session.get(key, default)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 393, in get
    num = len(clone)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 250, in __len__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")
[2025-02-21 10:17:54,051] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/jsi18n/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 190, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 583, in connect
    **kwargs)
  File "C:\Python372\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Python372\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\middleware.py", line 47, in process_response
    if request.session.get_expire_at_browser_close():
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 279, in get_expire_at_browser_close
    if self.get('_session_expiry') is None:
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 66, in get
    return self._session.get(key, default)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 393, in get
    num = len(clone)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 250, in __len__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。)")
[2025-02-21 10:17:54,058] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/jsi18n/ 500 [0.68, 127.0.0.1:52431]
[2025-02-21 10:17:54,181] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:52431]
[2025-02-21 11:07:20,233] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/userinfo/ 200 [0.91, 127.0.0.1:50874]
[2025-02-21 11:07:20,270] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.92, 127.0.0.1:51550]
[2025-02-21 11:07:20,318] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:50874]
[2025-02-21 11:11:38,454] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:52903]
[2025-02-21 13:11:39,185] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [1.27, 127.0.0.1:65076]
[2025-02-21 13:11:40,586] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [1.23, 127.0.0.1:65076]
[2025-02-21 13:11:40,647] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:65076]
[2025-02-21 13:11:40,817] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:65076]
[2025-02-21 13:12:09,728] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/menu/ 200 [0.11, 127.0.0.1:65076]
[2025-02-21 13:12:09,760] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:65083]
[2025-02-21 13:12:09,800] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:65076]
[2025-02-21 13:12:15,522] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.03, 127.0.0.1:65076]
[2025-02-21 13:12:15,531] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55850]
[2025-02-21 13:12:15,740] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:65484]
[2025-02-21 13:12:15,745] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65484]
[2025-02-21 13:12:15,919] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:65076]
[2025-02-21 13:12:22,935] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Property/ 200 [0.05, 127.0.0.1:65076]
[2025-02-21 13:12:22,973] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Property/ 200 [0.02, 127.0.0.1:65076]
[2025-02-21 13:12:22,985] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65484]
[2025-02-21 13:12:23,184] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:49178]
[2025-02-21 13:12:23,191] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:49178]
[2025-02-21 13:12:23,485] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 13:12:23 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /Navigations_Category/ POST
[2025-02-21 13:12:23,495] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_Category/ 200 [0.04, 127.0.0.1:65076]
[2025-02-21 13:12:23,526] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:65083]
[2025-02-21 13:12:27,177] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/Adapter/ 200 [0.04, 127.0.0.1:65083]
[2025-02-21 13:12:27,227] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/Adapter/ 200 [0.04, 127.0.0.1:65083]
[2025-02-21 13:12:27,234] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:49178]
[2025-02-21 13:12:27,283] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:49231]
[2025-02-21 13:12:27,286] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:49231]
[2025-02-21 13:12:27,373] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 13:12:27 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /Navigations_system/ POST
[2025-02-21 13:12:27,388] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_system/ 200 [0.05, 127.0.0.1:65083]
[2025-02-21 13:12:27,451] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.11, 127.0.0.1:65076]
[2025-02-21 13:13:04,387] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.05, 127.0.0.1:65076]
[2025-02-21 13:13:04,396] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:49231]
[2025-02-21 13:13:04,448] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50450]
[2025-02-21 13:13:04,456] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50450]
[2025-02-21 13:13:04,577] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:65076]
[2025-02-21 13:13:05,982] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Budget/ 200 [0.03, 127.0.0.1:65076]
[2025-02-21 13:13:06,062] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Budget/ 200 [0.07, 127.0.0.1:65076]
[2025-02-21 13:13:06,069] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50450]
[2025-02-21 13:13:06,117] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50469]
[2025-02-21 13:13:06,128] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50469]
[2025-02-21 13:13:06,186] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 13:13:06 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /Navigations_Category/ POST
[2025-02-21 13:13:06,200] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_Category/ 200 [0.02, 127.0.0.1:65076]
[2025-02-21 13:13:06,246] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:65083]
[2025-02-21 13:13:07,140] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/CapitalExpenditure/ 200 [0.05, 127.0.0.1:65083]
[2025-02-21 13:13:07,207] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/CapitalExpenditure/ 200 [0.06, 127.0.0.1:65083]
[2025-02-21 13:13:07,217] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50469]
[2025-02-21 13:13:07,266] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50512]
[2025-02-21 13:13:07,272] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50512]
[2025-02-21 13:13:07,337] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 13:13:07 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /Navigations_system/ POST
[2025-02-21 13:13:07,348] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_system/ 200 [0.02, 127.0.0.1:65083]
[2025-02-21 13:13:07,436] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.11, 127.0.0.1:65076]
[2025-02-21 13:13:08,746] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.28, 127.0.0.1:65076]
[2025-02-21 13:13:08,796] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/css/index.css 304 [0.01, 127.0.0.1:65076]
[2025-02-21 13:13:08,846] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50540]
[2025-02-21 13:13:08,848] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50540]
[2025-02-21 13:13:09,100] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 13:13:09 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /CapitalExpenditure/CapitalExpenditure_Summary/ POST
[2025-02-21 13:13:09,112] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.08, 127.0.0.1:65076]
[2025-02-21 13:13:09,117] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/css/fonts/element-icons.woff 304 [0.07, 127.0.0.1:65083]
[2025-02-21 13:13:09,183] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:65083]
[2025-02-21 15:37:11,546] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 15:37:11 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /CapitalExpenditure/CapitalExpenditure_Summary/ POST
[2025-02-21 15:37:11,565] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.32, 127.0.0.1:54890]
[2025-02-21 15:58:57,713] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.08, 127.0.0.1:59538]
[2025-02-21 15:58:57,721] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50540]
[2025-02-21 15:58:57,821] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59550]
[2025-02-21 15:58:57,824] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59550]
[2025-02-21 15:58:58,088] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 15:58:58 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /CapitalExpenditure/CapitalExpenditure_Summary/ POST
[2025-02-21 15:58:58,098] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.03, 127.0.0.1:59538]
[2025-02-21 15:58:58,147] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:59538]
[2025-02-21 15:59:07,384] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-02-21 15:59:07 C1010S3>Edwin None>None>None 127.0.0.1 127.0.0.1 /CapitalExpenditure/CapitalExpenditure_Summary/ POST
[2025-02-21 15:59:07,395] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CapitalExpenditure/CapitalExpenditure_Summary/ 200 [0.10, 127.0.0.1:59538]
[2025-02-21 17:15:31,414] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59550]
[2025-02-21 17:15:31,420] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50512]
