[2025-06-28 13:12:24,402] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /Lesson_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 2898, in Lesson_edit
    return render(request, '/Lesson_edit.html', locals())
  File "C:\Python3129\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /Lesson_edit.html
[2025-06-28 13:12:24,412] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /Lesson_edit/ 500 [0.46, 127.0.0.1:59865]
[2025-06-28 13:12:25,847] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /Lesson_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 2898, in Lesson_edit
    return render(request, '/Lesson_edit.html', locals())
  File "C:\Python3129\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /Lesson_edit.html
[2025-06-28 13:12:25,852] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /Lesson_edit/ 500 [0.07, 127.0.0.1:59865]
[2025-06-28 13:12:27,751] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /Lesson_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 2898, in Lesson_edit
    return render(request, '/Lesson_edit.html', locals())
  File "C:\Python3129\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /Lesson_edit.html
[2025-06-28 13:12:27,755] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /Lesson_edit/ 500 [0.04, 127.0.0.1:59865]
[2025-06-28 13:12:28,005] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /Lesson_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 2898, in Lesson_edit
    return render(request, '/Lesson_edit.html', locals())
  File "C:\Python3129\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /Lesson_edit.html
[2025-06-28 13:12:28,009] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /Lesson_edit/ 500 [0.07, 127.0.0.1:59865]
[2025-06-28 13:12:28,181] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /Lesson_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 2898, in Lesson_edit
    return render(request, '/Lesson_edit.html', locals())
  File "C:\Python3129\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python3129\mecheck\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /Lesson_edit.html
[2025-06-28 13:12:28,185] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /Lesson_edit/ 500 [0.05, 127.0.0.1:59865]
