[2024-12-02 13:19:56,669] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissuecrossresult/add/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`reliabilityrowdata`.`criticalissuecrosscheck_criticalissuecrossresult`, CONSTRAINT `CriticalIssueCrossCh_Projectinfo_id_f42441ef_fk_CriticalI` FOREIGN KEY (`Projectinfo_id`) REFERENCES `criti)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1564, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1091, in save_model
    obj.save()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`reliabilityrowdata`.`criticalissuecrosscheck_criticalissuecrossresult`, CONSTRAINT `CriticalIssueCrossCh_Projectinfo_id_f42441ef_fk_CriticalI` FOREIGN KEY (`Projectinfo_id`) REFERENCES `criti)')
[2024-12-02 13:19:56,714] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /admin/CriticalIssueCrossCheck/criticalissuecrossresult/add/ 500 [0.25, 127.0.0.1:54928]
[2024-12-02 13:59:24,387] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1717, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1400, in response_action
    response = func(self, request, queryset)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\actions.py", line 28, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1823, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\utils.py", line 134, in get_deleted_objects
    collector.collect(objs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\utils.py", line 197, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
TypeError: 'bool' object is not callable
[2024-12-02 13:59:24,408] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /admin/CriticalIssueCrossCheck/criticalissue/ 500 [1.31, 127.0.0.1:51733]
[2024-12-02 13:59:42,775] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1717, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1400, in response_action
    response = func(self, request, queryset)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\actions.py", line 28, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1823, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\utils.py", line 134, in get_deleted_objects
    collector.collect(objs)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\utils.py", line 197, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
TypeError: 'bool' object is not callable
[2024-12-02 13:59:42,778] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /admin/CriticalIssueCrossCheck/criticalissue/ 500 [0.07, 127.0.0.1:51733]
[2024-12-02 14:01:45,627] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/add/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 163, in __getitem__
    field = self.fields[name]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 118, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 130, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 169, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: "Key 'id' not found in 'CriticalIssueForm'. Choices are: Action, CG, Category, Object, Photo, Project, Reproduce_Steps, Root_Cause, Solution, Status, Symptom, edit_time, editor, video."
[2024-12-02 14:01:45,660] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CriticalIssueCrossCheck/criticalissue/add/ 500 [0.54, 127.0.0.1:57467]
[2024-12-02 14:03:55,225] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/add/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 163, in __getitem__
    field = self.fields[name]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 118, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 130, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 169, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: "Key 'id' not found in 'CriticalIssueForm'. Choices are: Action, CG, Category, Object, Photo, Project, Reproduce_Steps, Root_Cause, Solution, Status, Symptom, edit_time, editor, video."
[2024-12-02 14:03:55,233] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CriticalIssueCrossCheck/criticalissue/add/?_changelist_filters=o%3D-1.-13 500 [0.24, 127.0.0.1:54978]
[2024-12-02 14:09:00,651] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/add/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 163, in __getitem__
    field = self.fields[name]
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 118, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 130, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 169, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: "Key 'id' not found in 'CriticalIssueForm'. Choices are: Action, CG, Category, Object, Photo, Project, Reproduce_Steps, Root_Cause, Solution, Status, Symptom, edit_time, editor, video."
[2024-12-02 14:09:00,664] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CriticalIssueCrossCheck/criticalissue/add/ 500 [0.44, 127.0.0.1:56347]
[2024-12-02 15:15:51,542] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /ProjectInfoSearch/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 352, in ProjectInfoSearch
    print(str(UserInfo.objects.filter(account=ProjectinfoinDCT.objects.filter(ComPrjCode='ForTest1').first().DQAPLNum).email))
AttributeError: 'QuerySet' object has no attribute 'email'
[2024-12-02 15:15:51,569] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /ProjectInfoSearch/ 500 [0.43, 127.0.0.1:49311]
