[2025-07-11 12:39:50,945] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CommonFiles/CommonFiles_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CommonFiles\views.py", line 505, in CommonFiles_edit
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ManyRelatedManager is not JSON serializable
[2025-07-11 12:39:50,950] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /CommonFiles/CommonFiles_edit/ 500 [0.35, 127.0.0.1:50010]
