[2025-07-09 11:01:06,691] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /CommonFiles/CommonFiles_edit/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'Dev_Status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\CommonFiles\views.py", line 130, in CommonFiles_edit
    for i in CommonFiles._meta.get_field('Dev_Status').choices:
  File "C:\Python3129\mecheck\lib\site-packages\django\db\models\options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: CommonFiles has no field named 'Dev_Status'
[2025-07-09 11:01:06,693] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /CommonFiles/CommonFiles_edit/ 500 [0.08, 127.0.0.1:53881]
[2025-07-09 15:57:11,247] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CommonFiles/commonfiles/3/change/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 703, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 149, in fields_for_model
    f.name, model.__name__)
django.core.exceptions.FieldError: 'created_at' cannot be specified for CommonFiles model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1640, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1554, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 707, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: 'created_at' cannot be specified for CommonFiles model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class CommonFilesAdmin.
[2025-07-09 15:57:11,254] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CommonFiles/commonfiles/3/change/ 500 [0.11, 127.0.0.1:61298]
[2025-07-09 15:58:52,775] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CommonFiles/commonfiles/3/change/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 703, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 149, in fields_for_model
    f.name, model.__name__)
django.core.exceptions.FieldError: 'updated_at' cannot be specified for CommonFiles model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1640, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1554, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 707, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: 'updated_at' cannot be specified for CommonFiles model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class CommonFilesAdmin.
[2025-07-09 15:58:52,778] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CommonFiles/commonfiles/3/change/ 500 [0.03, 127.0.0.1:61406]
[2025-07-09 15:58:57,442] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CommonFiles/commonfiles/3/change/
Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 703, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "C:\Python3129\mecheck\lib\site-packages\django\forms\models.py", line 149, in fields_for_model
    f.name, model.__name__)
django.core.exceptions.FieldError: 'updated_at' cannot be specified for CommonFiles model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python3129\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1640, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 1554, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "C:\Python3129\mecheck\lib\site-packages\django\contrib\admin\options.py", line 707, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: 'updated_at' cannot be specified for CommonFiles model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class CommonFilesAdmin.
[2025-07-09 15:58:57,448] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CommonFiles/commonfiles/3/change/ 500 [0.09, 127.0.0.1:61406]
